# Generated by Django 3.2.16 on 2022-10-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_firm_product_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
