# Generated by Django 3.2.16 on 2022-10-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_firm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
